[package]
name = "executor"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
tracing.workspace = true
vise.workspace = true

zksync_protobuf.workspace = true
concurrency = { path = "../../libs/concurrency" }
crypto = { path = "../../libs/crypto" }
roles = { path = "../../libs/roles" }
schema = { path = "../../libs/schema" }
storage = { path = "../../libs/storage" }
utils = { path = "../../libs/utils" }

consensus = { path = "../consensus" }
network = { path = "../network" }
sync_blocks = { path = "../sync_blocks" }

[dev-dependencies]
rand.workspace = true
tokio.workspace = true
